<a href="https://colab.research.google.com/github/patilhumesh88-spec/ASSIGNMENT/blob/main/chapter_appendix-tools-for-deep-learning/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ASSIGNMENT 1

In [1]:
import numpy as np

In [6]:
integers=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])# declaring the integers
arr=integers#variabilization of integers
array_sum=np.sum(arr)# defining the arrays in .np way
array_mean=np.mean(arr)
array_meadian=np.median(arr)
array_std_dev=np.std(arr)
print(f"Sum of the array:{array_sum}")# by the help of f function type giving their values and the result that should be printed in it
print(f"Mean of the array:{array_mean}")
print(f"Median of the array:{array_meadian}")
print(f"Standard deviation of the array:{array_std_dev}")
indices_greater_than_10=np.where(arr>10)
print(f"Indices of elements greater than 10:{indices_greater_than_10[0]}")#for the indices getting the value by applying a simple condition



Sum of the array:210
Mean of the array:10.5
Median of the array:10.5
Standard deviation of the array:5.766281297335398
Indices of elements greater than 10:[10 11 12 13 14 15 16 17 18 19]


In [16]:
array_2d=np.arange(1,17).reshape(4,4)#creating the 2D 4by4 array that is needed
print(array_2d)
array_2d_transpose=array_2d.T# for thr transpose adding .T at te end of the numpy function
print("\nTranspose of the array:")
print(array_2d_transpose)
row_sums=np.sum(array_2d,axis=1) #
print("\nRow-wise sums:")
print(row_sums)
column_sums=np.sum(array_2d,axis=0)
print("\nColumn-wise sums:")
print(column_sums)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose of the array:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Row-wise sums:
[10 26 42 58]

Column-wise sums:
[28 32 36 40]


In [ ]:
import numpy as np

# Create two 3x3 arrays filled with random integers between 1 and 20
array_a = np.random.randint(1, 21, size=(3, 3))
array_b = np.random.randint(1, 21, size=(3, 3))

print("Array A:")
print(array_a)
print("\nArray B:")
print(array_b)

# Perform element-wise addition
addition_result = array_a + array_b
print("\nElement-wise Addition (A + B):")
print(addition_result)

# Perform element-wise subtraction
subtraction_result = array_a - array_b
print("\nElement-wise Subtraction (A - B):")
print(subtraction_result)

# Perform element-wise multiplication
multiplication_result = array_a * array_b
print("\nElement-wise Multiplication (A * B):")
print(multiplication_result)

# Compute the dot product of the two arrays
dot_product_result = np.dot(array_a, array_b)
print("\nDot Product of A and B:")
print(dot_product_result)