<a href="https://colab.research.google.com/github/patilhumesh88-spec/ASSIGNMENT/blob/main/chapter_appendix-tools-for-deep-learning/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ASSIGNMENT 1

In [ ]:
import numpy as np

In [ ]:
integers=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])# declaring the integers
arr=integers#variabilization of integers
array_sum=np.sum(arr)# defining the arrays in .np way
array_mean=np.mean(arr)
array_meadian=np.median(arr)
array_std_dev=np.std(arr)
print(f"Sum of the array:{array_sum}")# by the help of f function type giving their values and the result that should be printed in it
print(f"Mean of the array:{array_mean}")
print(f"Median of the array:{array_meadian}")
print(f"Standard deviation of the array:{array_std_dev}")
indices_greater_than_10=np.where(arr>10)
print(f"Indices of elements greater than 10:{indices_greater_than_10[0]}")#for the indices getting the value by applying a simple condition



Sum of the array:210
Mean of the array:10.5
Median of the array:10.5
Standard deviation of the array:5.766281297335398
Indices of elements greater than 10:[10 11 12 13 14 15 16 17 18 19]


In [ ]:
array_2d=np.arange(1,17).reshape(4,4)#creating the 2D 4by4 array that is needed
print(array_2d)
array_2d_transpose=array_2d.T# for thr transpose adding .T at te end of the numpy function
print("\nTranspose of the array:")#inthe transpose the rows become colummns and columns become rows
print(array_2d_transpose)
row_sums=np.sum(array_2d,axis=1) #in this code to get the sum we have add up the rows
print("\nRow-wise sums:")
print(row_sums)
column_sums=np.sum(array_2d,axis=0)# in this tghe sum of the columns is done
print("\nColumn-wise sums:")
print(column_sums)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose of the array:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Row-wise sums:
[10 26 42 58]

Column-wise sums:
[28 32 36 40]


In [9]:
import numpy as np
#making two random 3*3 a and 1 to 20 arrays of 3D
array_a=np.random.randint(1,21,size=(3,3))
array_b=np.random.randint(1,21,size=(3,3))
print("Array_A:")
print(array_a)
print("\nArray_B:")
print(array_b)

addition_result=array_a+array_b#making array a and b addition by '+'
print("\nElement-wise Addition (A+B):")
print(addition_result)

subtraction_result=array_a-array_b#making array a and b subtract by'-'
print("\nElement-wise Subtraction (A-B):")
print(subtraction_result)

multiplication_result=array_a*array_b# making array a and b multiply each other by the help of'*'
print("\nElement-wise Multiplication (A*B)")
print(multiplication_result)

dot_product_result=np.dot(array_a,array_b)
print("\nDot Product of A and B:")
print(dot_product_result)

Array_A:
[[20  2  4]
 [16 15 15]
 [ 1 20  6]]

Array_B:
[[ 8 15  2]
 [ 6 14  1]
 [12  3 16]]

Element-wise Addition (A+B):
[[28 17  6]
 [22 29 16]
 [13 23 22]]

Element-wise Subtraction (A-B):
[[ 12 -13   2]
 [ 10   1  14]
 [-11  17 -10]]

Element-wise Multiplication (A*B)
[[160  30   8]
 [ 96 210  15]
 [ 12  60  96]]

Dot Product of A and B:
[[220 340 106]
 [398 495 287]
 [200 313 118]]


In [11]:
arr_1d=np.arange(1,13)
print("Original 1D array:\n",arr_1d)

arr_2d=arr_1d.reshape(3,4)
print("\Reshaped 3x4 2D array:\n", arr_2d)
sliced_array=arr_2d[:2,2:]
print("\nsliced array (first two rows,last two column):\n",sliced_array)

Original 1D array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
\Reshaped 3x4 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

sliced array (first two rows,last two column):
 [[3 4]
 [7 8]]


<>:5: SyntaxWarning: invalid escape sequence '\R'
<>:5: SyntaxWarning: invalid escape sequence '\R'
/tmp/ipython-input-2238402521.py:5: SyntaxWarning: invalid escape sequence '\R'
  print("\Reshaped 3x4 2D array:\n", arr_2d)
